version: '3'

services:
  api:
    container_name: jupyter-lab
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .${WORKDIR}:${WORKDIR}
    command: jupyter-lab --ip=${HOST} --port=${PORT} --allow-root --LabApp.token=''
    ports:
      - ${PORT}:${PORT}
    env_file:
      - ./.env
    environment:
      WORKDIR: ${WORKDIR}
      HOST: ${HOST}
      PORT: ${PORT}
      DEBUG: ${DEBUG}
      LANG: ${LANG}
      LC_ALL: ${LC_ALL}
      PYTHONUNBUFFERED: ${PYTHONUNBUFFERED}
      PYTHONIOENCODING: ${PYTHONIOENCODING}
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
