version: '3'

services:
  api:
    container_name: fastapi
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .${WORKDIR}:${WORKDIR}
    command: uvicorn main:app --host ${HOST} --port ${PORT} --reload
    ports:
      - ${PORT}:${PORT}
    env_file:
      - ./.env
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      DEBUG: ${DEBUG}
      LC_ALL: ${LC_ALL}
      PYTHONUNBUFFERED: ${PYTHONUNBUFFERED}
      PYTHONIOENCODING: ${PYTHONIOENCODING}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    image: mysql:latest
    container_name: fastapi-db
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
    env_file:
      - ./.env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    tty: true
    # restart: always

volumes:
  mysql:
  mysql_config:
