version: '3'

services:
  api:
    container_name: jupyter-lab
    build: ./
    tty: true
    command: jupyter-lab --ip=0.0.0.0 --port=8888 --allow-root --LabApp.token=''
    volumes:
      - ./code:/code
    ports:
      - "8888:8888"
    env_file:
      - ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
