FROM ubuntu:18.04
RUN apt-get update && \
    apt-get install -y \
    vim \
    curl \
    sudo \
    wget \
    nodejs
RUN npm && \
    npm install n -g && \
    n stable && \
    apt purge -y nodejs npm
RUN mkdir /code
WORKDIR /code
ENV NODE_ENV=developments
EXPOSE 3000
