FROM ubuntu:18.04
RUN apt-get update && apt-get update && apt-get install -y \
    git \
    vim \
    zip \
    curl \
    sudo \
    unzip \
    python3.8 \
    python3-pip
RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/
COPY .jupyter/lab/ /root/.jupyter/lab/
RUN pip3 install --upgrade pip && \
    pip3 install -r requirements.txt
